clouds=fast
oldLighting=true
underwaterOverlay=false
vignette=false
shadowDistanceRenderMul=1.0

sliders=EXPOSURE SATURATION CONTRAST VIGNETTE_STRENGTH WARMTH_STRENGTH FOG_START WAVE_AMPLITUDE NIGHT_MIN_LIGHT shadowMapResolution shadowDistance

screen=EXPOSURE SATURATION CONTRAST VIGNETTE_STRENGTH WARMTH_STRENGTH <empty> FOG_START NIGHT_MIN_LIGHT WATER_WAVES WAVE_AMPLITUDE <empty> SHADOWS shadowMapResolution shadowDistance

screen.EXPOSURE=Exposicao
screen.SATURATION=Saturacao
screen.CONTRAST=Contraste
screen.VIGNETTE_STRENGTH=Vinheta
screen.WARMTH_STRENGTH=Calor no por do sol
screen.FOG_START=Inicio da nevoa
screen.NIGHT_MIN_LIGHT=Luz minima noturna
screen.WATER_WAVES=Ondas na agua
screen.WAVE_AMPLITUDE=Altura das ondas
screen.SHADOWS=Sombras
screen.shadowMapResolution=Resolucao das sombras
screen.shadowDistance=Alcance das sombras
